#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook "ntp"
cookbook "openssh"
cookbook "php"
#cookbook "apache2", :git => "git://github.com/tolleiv/apache2.git", :ref => "COOK-1984"
cookbook "apache2"
#cookbook "mysql", :git => "git://github.com/opscode-cookbooks/mysql.git"
cookbook "mysql"
cookbook "apt", :git => "git://github.com/opscode-cookbooks/apt.git"
cookbook "git"
cookbook "composer"

# install oh-my-zsh
cookbook "chef-oh-my-zsh",
    :git => "git://github.com/tlayh/chef-oh-my-zsh.git"

# install cucmber
cookbook "tl-cucumber",
    :git => "git://github.com/tlayh/tl-cucumber.git"